twig:
    default_path: '%kernel.project_dir%/templates'
    date:
        format: d F Y
        interval_format: '%%d days'
    form_themes: ['shared/layout/form_theme.html.twig']
    globals:
        mercure_subscribe_url: '%env(resolve:MERCURE_PUBLIC_URL)%'

when@test:
    twig:
        strict_variables: true
