vich_uploader:
    db_driver: orm

    mappings:
        reports:
            uri_prefix: /documents/reports
            upload_destination: '%kernel.project_dir%/public/uploads/reports'
            namer:
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options: { property: 'id', transliterate: true }
